name: Reusable Workflow2

on:
  workflow_call:
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Input
        run: echo "Input received call testing from testing workflow next"
